-- QueryGate synthetic EHR/claims schema (spec §8).
--
-- All application tables live in a dedicated `app` schema (NOT public), so the
-- least-privilege role gets USAGE on `app` only and `public` stays write-locked.
-- Tables are owned by the admin/migration role that runs this file; the read-only
-- `querygate` role never owns anything, so it cannot DROP or ALTER them.
--
-- Idempotent: safe to run repeatedly (CREATE ... IF NOT EXISTS). Structure only —
-- data is loaded by scripts/seed.py.

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.patients (
    patient_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text        NOT NULL,
    dob               date        NOT NULL,
    sex               text        NOT NULL,
    city              text        NOT NULL,
    registered_at     timestamptz NOT NULL,
    last_contacted_at timestamptz             -- nullable: not every patient has been contacted
);

CREATE TABLE IF NOT EXISTS app.providers (
    provider_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    specialty   text NOT NULL,
    npi         text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.encounters (
    encounter_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   integer NOT NULL REFERENCES app.patients (patient_id),
    provider_id  integer NOT NULL REFERENCES app.providers (provider_id),
    date         date    NOT NULL,
    type         text    NOT NULL,
    status       text    NOT NULL
);

CREATE TABLE IF NOT EXISTS app.claims (
    claim_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id integer        NOT NULL REFERENCES app.encounters (encounter_id),
    amount       numeric(12, 2) NOT NULL,
    status       text           NOT NULL,
    submitted_at timestamptz    NOT NULL,
    paid_at      timestamptz                -- nullable: unpaid/denied claims have no paid date
);

CREATE TABLE IF NOT EXISTS app.follow_ups (
    follow_up_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   integer NOT NULL REFERENCES app.patients (patient_id),
    due_date     date    NOT NULL,
    completed_at timestamptz                -- nullable: NULL = not yet completed (overdue if past due)
);
